### ISSUE TITLE
libalpm.so.13 could not determine kind of name for C.alpm_option_set_arch

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [Jguer/go-alpm#49] opened 2021-06-09 16:44 UTC
When compiling it runs into this issue, here are the logs:
```
/home/ben/go/pkg/mod/github.com/!jguer/go-alpm/v2@v2.0.5/handle_five.go:20:10: could not determine kind of name for C.alpm_option_get_arch
/home/ben/go/pkg/mod/github.com/!jguer/go-alpm/v2@v2.0.5/handle_five.go:26:10: could not determine kind of name for C.alpm_option_set_arch
```
I assume it's just a matter of looking at libalpm and finding the new name for this function or just making a workaround. I'm not entirely sure what it does, but by its name I assume it's for setting the package architecture. I will search for it in the libalpm repository and see what I can find.

**Comment by AnonFuncsAreAwesome** [comment] 2021-06-10 16:27
This is already fixed with https://github.com/Jguer/go-alpm/commit/0cea2809fc21b841f2ce9e83805a7d93f7eba4fc, so a duplicate of #43.

If you don't use the Makefile, you have to add `-tags six` to your GOFLAGS, that should fix it.

**Closed** 2021-07-03 15:55 UTC
